apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-django-app
  template:
    metadata:
      labels:
        app: my-django-app
    spec:
      containers:
        - name: my-django-app
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-django-app:${{ github.sha }}
          ports:
            - containerPort: 8000
