apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-django-app-ingress
spec:
  rules:
    - host: your.domain.com  # Replace with your domain or public IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-django-app-service
                port:
                  number: 80
