name: Deploy to GKE

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker CLI
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${HOME}/gcp-key.json
          docker login -u _json_key --password-stdin https://gcr.io < ${HOME}/gcp-key.json
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-django-app:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-django-app:${{ github.sha }}
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCR_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-django-app:${{ github.sha }}

      - name: Authenticate with GKE
        run: gcloud auth configure-docker

      - name: Set kubectl context
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}
        
      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
        env:
          GCR_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-django-app:${{ github.sha }}
